import type {CSSProperties} from "react";
import type {LocalSave, TrainerCatalogState} from "@changebattle/shared";
import type {MoveCardData} from "../components/move/MoveCard";

export const moveCardPreviewData: Record<string, MoveCardData & {size?: "battle" | "sheet" | "dex" | "draw"; selected?: boolean; disabled?: boolean; className?: string; previewWidth?: number; style?: CSSProperties}> = {
  dex: {
    name: "日光束",
    moveType: "grass",
    typeLabel: "草",
    category: "特殊",
    pp: 10,
    power: 120,
    accuracy: 100,
    size: "dex",
    className: "quick-dex-move-card",
  },
  battle: {
    name: "暴风",
    moveType: "flying",
    typeLabel: "飞行",
    category: "特殊",
    pp: 15,
    maxPp: 16,
    power: 110,
    accuracy: 70,
    size: "battle",
  },
  complete: {
    name: "暴风",
    moveType: "flying",
    typeLabel: "飞行",
    category: "物理",
    pp: 15,
    maxPp: 16,
    power: 110,
    accuracy: 70,
    damageRange: "107%~127%",
    badge: "效果拔群",
    size: "battle",
    selected: true,
  },
  longText: {
    name: "超长名字测试技能光合作用极限爆发",
    moveType: "psychic",
    typeLabel: "超能力",
    category: "特殊",
    pp: 5,
    maxPp: 8,
    power: "变化",
    accuracy: "必中",
    damageRange: "伤害范围显示很长",
    badge: "不可替换",
    size: "dex",
    className: "quick-dex-move-card quick-dex-result-move-card",
  },
  disabled: {
    name: "破坏光线",
    moveType: "normal",
    typeLabel: "一般",
    category: "特殊",
    pp: 0,
    maxPp: 8,
    power: 150,
    accuracy: 90,
    size: "battle",
    disabled: true,
  },
  compact: {
    name: "电光一闪",
    moveType: "normal",
    typeLabel: "一般",
    category: "物理",
    pp: 30,
    power: 40,
    accuracy: 100,
    size: "sheet",
    previewWidth: 160,
    style: {
      "--move-card-height": "22px",
      "--move-card-name-row-height": "12px",
      "--move-card-meta-row-height": "8px",
      "--move-card-name-font-size": "5px",
      "--move-card-meta-font-size": "4px",
      "--move-card-badge-font-size": "4px",
      "--move-card-name-padding-x": "3px",
      "--move-card-meta-padding-x": "3px",
    } as CSSProperties,
  },
  wide: {
    name: "十万伏特",
    moveType: "electric",
    typeLabel: "电",
    category: "特殊",
    pp: 15,
    maxPp: 24,
    power: 90,
    accuracy: 100,
    damageRange: "64%~76%",
    badge: "稳定输出",
    size: "battle",
    previewWidth: 420,
    style: {
      "--move-card-height": "38px",
      "--move-card-name-row-height": "24px",
      "--move-card-meta-row-height": "11px",
      "--move-card-name-font-size": "9px",
      "--move-card-meta-font-size": "7px",
    } as CSSProperties,
  },
  tall: {
    name: "流星群",
    moveType: "dragon",
    typeLabel: "龙",
    category: "特殊",
    pp: 5,
    maxPp: 8,
    power: 130,
    accuracy: 90,
    damageRange: "88%~104%",
    badge: "降特攻",
    size: "draw",
    previewWidth: 260,
    style: {
      "--move-card-height": "54px",
      "--move-card-name-row-height": "34px",
      "--move-card-meta-row-height": "17px",
      "--move-card-name-font-size": "9px",
      "--move-card-meta-font-size": "7px",
      "--move-card-badge-font-size": "6px",
    } as CSSProperties,
  },
};

export const titlePreviewCatalog: TrainerCatalogState = {
  players: [
    {id: "may", type: "player", name_en: "May", name_zh: "小遥", avatar_asset: "trainers/avatars/may.png", front_asset: "trainers/front/may.png", front_gif_asset: "trainers/front/may.gif"},
    {id: "brendan", type: "player", name_en: "Brendan", name_zh: "小悠", avatar_asset: "trainers/avatars/brendan.png", front_asset: "trainers/front/brendan.png", front_gif_asset: "trainers/front/brendan.gif"},
    {id: "leaf", type: "player", name_en: "Leaf", name_zh: "叶子", avatar_asset: "trainers/avatars/leaf.png", front_asset: "trainers/front/leaf.png", front_gif_asset: "trainers/front/leaf.gif"},
    {id: "red", type: "player", name_en: "Red", name_zh: "赤红", avatar_asset: "trainers/avatars/red.png", front_asset: "trainers/front/red.png", front_gif_asset: "trainers/front/red.gif"},
  ],
  avatars: [
    {id: "avatar-may", type: "avatar", name_en: "May", name_zh: "小遥", avatar_asset: "trainers/avatars/may.png"},
    {id: "avatar-brendan", type: "avatar", name_en: "Brendan", name_zh: "小悠", avatar_asset: "trainers/avatars/brendan.png"},
    {id: "avatar-leaf", type: "avatar", name_en: "Leaf", name_zh: "叶子", avatar_asset: "trainers/avatars/leaf.png"},
    {id: "avatar-red", type: "avatar", name_en: "Red", name_zh: "赤红", avatar_asset: "trainers/avatars/red.png"},
    {id: "avatar-cynthia", type: "avatar", name_en: "Cynthia", name_zh: "竹兰", avatar_asset: "trainers/avatars/cynthia.png"},
  ],
};

export function createTitlePreviewSave(name = "小遥", battlePoints = 128): LocalSave {
  return {
    version: 1,
    trainer: {
      name,
      player_npc_id: "may",
      avatar_asset: "trainers/avatars/may.png",
      front_asset: "trainers/front/may.png",
      front_gif_asset: "trainers/front/may.gif",
    },
    stats: {
      battle_points: battlePoints,
      battles: 12,
      wins: 8,
      losses: 4,
      rank_status: "normal",
    },
    current_run: null,
    created_at: "2026-06-14T00:00:00.000Z",
    updated_at: "2026-06-14T00:00:00.000Z",
  };
}
